### PR TITLE
version 1.6, - new search, infinite map handling, etc

### PR DESCRIPTION
**Pull request by wsrvn**
merge to main whenever ready.

current changes: 
1. hypothetically infinite maps handling on the server
2. way faster search
3. nickname->player translation in admin commands
4. various ui fixes
5. some small bug fixes

### CODE REVIEW

**Comment by wsrvn** [comment]
#254 & #252 should probably be fixed before merge. dunno about #245.

**Comment by wsrvn** [comment]
todo: admin windows' refresh on privilege update broke again (somehow), gotta fix that..

**Review by felacek — APPROVED** [review]
LGTM, i think we should honestly just push this update now so we can start refactoring some of the uglier services (map, records etc.)

**Review by lythx — APPROVED** [review]
Looks good

**Comment by felacek** [comment]
It seems docker cannot build rn because of [this bug](https://github.com/leeoniya/uFuzzy/issues/70), even though everything was fine 2 weeks ago... Maybe they release the update to npm soon? Otherwise we'll have to actually solve this ourselves

**Review by felacek — APPROVED** [review]
works on my machine...

**Review by lythx — APPROVED** [review]
nice Code. Great Fortune

**Pull request merged**
